"""Some fixes

Revision ID: 0b793b1eb3f3
Revises: 1b6338fd485e
Create Date: 2022-11-16 19:05:10.736999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b793b1eb3f3'
down_revision = '1b6338fd485e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.String(length=32), nullable=False))
    op.drop_column('user', 'roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('roles', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
