"""create

Revision ID: 0d7ffaae3715
Revises: 
Create Date: 2022-11-02 16:21:05.416290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7ffaae3715'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airport',
    sa.Column('airport_id', sa.Integer(), nullable=False),
    sa.Column('aiport_name', sa.String(length=45), nullable=False),
    sa.Column('city', sa.String(length=45), nullable=False),
    sa.Column('country', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('airport_id'),
    sa.UniqueConstraint('aiport_name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('firstname', sa.String(length=20), nullable=False),
    sa.Column('lastname', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('flight',
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('flight_no', sa.String(length=45), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('cost_of_flight', sa.Float(), nullable=False),
    sa.Column('num_of_seats', sa.Integer(), nullable=False),
    sa.Column('arriving_airport_id', sa.Integer(), nullable=True),
    sa.Column('departing_airport_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['arriving_airport_id'], ['airport.airport_id'], ),
    sa.ForeignKeyConstraint(['departing_airport_id'], ['airport.airport_id'], ),
    sa.PrimaryKeyConstraint('flight_id'),
    sa.UniqueConstraint('flight_no')
    )
    op.create_table('passenger',
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=20), nullable=False),
    sa.Column('lastname', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('passport_number', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('passenger_id'),
    sa.UniqueConstraint('passport_number')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_done_datetime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=45), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('passenger_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.flight_id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['passenger.passenger_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('passenger')
    op.drop_table('flight')
    op.drop_table('user')
    op.drop_table('airport')
    # ### end Alembic commands ###
