"""Changed field delete

Revision ID: afa5a36392d6
Revises: 0b793b1eb3f3
Create Date: 2022-11-18 11:08:57.075291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa5a36392d6'
down_revision = '0b793b1eb3f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
